# -*- coding: utf-8 -*-
"""Assignment02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pQp_JVH1JfKCR21bJTkLmgHjwfgO3Gjr
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import skit-learn as

from google.colab import drive
drive.mount('/content/drive')

df=pd.read_csv('/content/Housing.csv')
df.head()

df[['price','area','bedrooms','bathrooms','mainroad','guestroom']].describe()

sns.histplot(df.price,kde=True)

df[['price','area','bedrooms','bathrooms','mainroad','guestroom']].corr()

sns.scatterplot(df.area)
plt.ylim(0,20000)

sns.pairplot(df[['price','area','bedrooms','bathrooms','mainroad','guestroom']],hue='area')

#descriptive static analyse

df.describe()

df.mean()

df.mode()

df.median()

df.info()

average = df['area'].mean()
print(average)
med = df['area'].median()
print(med)

#Missing values

df.shape

df.isnull()

df.isnull().sum()

df.isnull().sum().sum()

# Outliers

sns.boxplot(df.price)

# Spilit the dataset

X = df.iloc[:, :-1].values
print(X)

Y = df.iloc[:, -1].values
print(Y)

#train & test

training_data = df.sample(frac=0.8, random_state=25)
testing_data = df.drop(training_data.index)

print(f"No. of training examples: {training_data.shape[0]}")
print(f"No. of testing examples: {testing_data.shape[0]}")